version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-atahack-frontend
    volumes:
      - ./dist/datahack-frontend/:/app/html
      - ./nginx/:/etc/nginx/
    ports:
      - "7071:80"
